### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by JazzGlobal** [HopeMetal/2DTacticalRPGDemo#1]
Hey there, found your project on the asset store. I've been using it to learn Godot. Thanks for your work! I was wondering if I can merge some changes I implemented. 

- https://github.com/JazzGlobal/Godot-2D-Tactical-RPG/issues/1
- https://github.com/JazzGlobal/Godot-2D-Tactical-RPG/issues/3

Feel free to take the changes if you want them or I can open a PR if desired. 😁

**Comment by HopeMetal** [comment]
Sure, go ahead an make a PR.
