### ISSUE TITLE
Pathfinding bug

### ISSUE THREAD

**Issue by AzureJames** [HopeMetal/2DTacticalRPGDemo#3]
Both AI and players get caught forever in a fast loop of going back an forth about 5 pixels during pathfinding. Replicatable if you click around randomly during pathfinding. (/all the time) This could perhaps be fixed by limiting mouse actions except exactly when they're needed? Barring that maybe a timer could be implemented to stop pathfinding loops and then reset the character to an exact grid position? Also my grid is larger in case that causes the bug. cell_size = Vector2i(48, 48) _astargrid.offset = Vector2(24, 24)

**Comment by HopeMetal** [comment]
I can't replicate the bug with either grid size. Are you sure you haven't modified something else as well?

**Comment by AzureJames** [comment]
I fixed mine by disabling again on the enemy turn and when _arrived is false so if the base template is good then both of ours are good
