### ISSUE TITLE
Feature request: Flying unit support

### ISSUE THREAD

**Issue by Nyekomimi** [HopeMetal/2DTacticalRPGDemo#5]
Flying units are a staple - be it turning yourself into a bird, using a fantastic steed or a jetpack/helicopter.

Flying units can be differentiated in 2 ways - they can move through spaces occupied by enemy units (thanks to 3rd axis of movement), as well as be unaffected by most of terrain (moving over most terrain at same pace regardless of ("different costs for moving through terrain"), but still can't burst through ceilings (maybe handled by "blocking specific unit classes")

It's hard to understate the depth that flying units bring into the battlefield, preventing bottleneck-based strategies and potentially requiring additional planning - or providing additional options.

**Comment by HopeMetal** [comment]
Added support for flying units in the 1.1-dev branch. Currently only allows moving over enemies. The only restriction is that a flying unit cannot stop *on top* of another unit as that would make it confusing to overview the battlefield if there aree many units on 1 space.
