### ISSUE TITLE
Feature request: blocking specific unit classes

### ISSUE THREAD

**Issue by Nyekomimi** [HopeMetal/2DTacticalRPGDemo#6]
In all sort of games there tend to be restrictions as to what can get where. Most classic example is a cavalry unit not being able to enter a forest. 

This brings lot of potential scenarios - such as troops escaping into dense ruins where heavy vehicles cannot chase them.

**Comment by HopeMetal** [comment]
Added in 1.1-dev branch. Added a Mounted movement class, which is just like the Ground class except it can be used to separately block ground and mounted units. The TileSet now has a Blocks custom data layer, which can have multiple values corresponding to the movement class it should block. So its even possible to create tiles that Flying and Mounted units cannot pass, but regular Ground units can, or ones only a Flying unit can cross such as a chasm.

For testing purposes Steve was temporarily turned into a Mounted unit without different graphics, so he is no longer able to go on the T tile in the map.
